---
title: Agregue una variable en Scratch
hero_image: images / banner.png
description: Cómo agregar una variable en Scratch
original_url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Crea una variable
