---
title: Aggiungi una variabile in Scratch
hero_image: images / banner.png
description: Come aggiungere una variabile in Scratch
original_url: ""
theme: cc-prototipo
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Crea una variabile
